import Head from 'next/head';
import { Center } from '@chakra-ui/react';
import { Icon } from '@chakra-ui/react';
import { FiHome, FiSettings, FiFilm, FiHeart } from 'react-icons/fi';
import { DiYii } from 'react-icons/di';
import { useState } from 'react';

import styles from '../styles/Home.module.scss';

const menuItems = [
	{ name: 'home', icon: <FiHome /> },
	{ name: 'settings', icon: <FiSettings /> },
	{ name: 'film', icon: <FiFilm /> },
	{ name: 'like', icon: <FiHeart /> },
];

export default function Home() {
	const [selectedMenuItem, setSelectedMenuItem] = useState('home');

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<nav className={styles.nav}>
				<Center w='50px' h='50px' color={'#515151'} style={{ marginTop: '1rem', marginBottom: '1rem' }}>
					<Icon as={DiYii} className={styles.logo} />
				</Center>
				{menuItems.map((item) => (
					<div className={styles.nav_item}>
						<Center
							h='40px'
							className={styles[`icon${item.name === selectedMenuItem ? '--selected' : ''}`]}
							key={item.name}
							onClick={() => setSelectedMenuItem(item.name)}>
							{item.icon}
						</Center>
						<div id={`tooltip_${item.name}`} className={styles.nav_item_tooltip}>
							{item.name}
						</div>
					</div>
				))}
			</nav>
			<main className={styles.main}>
				<section className={styles.course}>
					<h1>Courses Smigol offers </h1>
					<p>There are a lot of courses available </p>
					<div className={styles.row}>
						<div className={styles["course-col"]}>
							<h3>FRANK</h3>
							<p>My little smoochy cutie pie</p>
						</div>
						<div className={styles["course-col"]}>
							<h3>PUZZETTA</h3>
							<p>My fluffy silly doggy</p>
						</div>
						<div className={styles["course-col"]}>
							<h3>NENE</h3>
							<p>My big sis</p>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
